//
// Seamless Sudo
//
// Copyright (C) 1995-2023, Yegor Mialyk. All Rights Reserved.
//
// Licensed under the MIT License. See the LICENSE file for details.
//

//
// <auto-generated>
//     This code was generated by a tool.
//     Pascal Preprocessor, version 0.08
//
//     Copyright (C) 1995-2023, Yegor Mialyk. All Rights Reserved.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//

const
  VERSION_STRING = '1.1.0';
  COPYRIGHT_STRING = 'Copyright (C) 1995-2023, Yegor Mialyk. All Rights Reserved.';

  APP_NAME = 'Seamless Sudo';
