//
// Seamless Sudo
//
// Copyright (C) 1995-2020, Yegor Mialyk. All Rights Reserved.
//
// Licensed under the MIT License. See the LICENSE file for details.
//

{$ALIGN ON}
{$ASSERTIONS OFF}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$DEFINITIONINFO OFF}
{$EXTENDEDCOMPATIBILITY OFF}
{$EXTENDEDSYNTAX ON}
{$EXCESSPRECISION ON}
{$HIGHCHARUNICODE OFF}
{$HINTS ON}
{$INLINE ON}
{$IOCHECKS OFF}
{$LOCALSYMBOLS OFF}
{$LONGSTRINGS ON}
{$METHODINFO OFF}
{$MINENUMSIZE 4}
{$OPTIMIZATION ON}
{$OVERFLOWCHECKS OFF}
{$POINTERMATH ON}
{$RANGECHECKS OFF}
{$REALCOMPATIBILITY OFF}
{$REFERENCEINFO OFF}
{$SAFEDIVIDE OFF}
{$STACKFRAMES OFF}
{$STRONGLINKTYPES OFF}
{$TYPEDADDRESS OFF}
{$TYPEINFO OFF}
{$VARSTRINGCHECKS OFF}
{$WARNINGS ON}
{$WEAKLINKRTTI ON}
{$WRITEABLECONST ON}
{$ZEROBASEDSTRINGS OFF}

{$WARN SYMBOL_PLATFORM OFF}
{$WARN UNIT_PLATFORM OFF}
{$WARN IMPLICIT_STRING_CAST ERROR}

{$IFDEF WIN32}
  {$SETPEFLAGS $20}
{$ENDIF}
